//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.24 at 11:00:11 AM MSK
//

package ru.akrtkv.egisz.vimis.dto.vimis;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "summary",
        "thesises"
})
@XmlRootElement(name = "clinrec")
public class Clinrec {

    @XmlElement(required = true)
    protected Summary summary;

    @XmlElement(required = true)
    protected Thesises thesises;

    public Summary getSummary() {
        return summary;
    }

    public void setSummary(Summary value) {
        this.summary = value;
    }

    public Thesises getThesises() {
        return thesises;
    }

    public void setThesises(Thesises value) {
        this.thesises = value;
    }

    @Override
    public String toString() {
        return "Clinrec{" +
                "summary=" + summary +
                ", thesises=" + thesises +
                '}';
    }
}
