//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.24 at 11:00:11 AM MSK
//

package ru.akrtkv.egisz.vimis.dto.vimis;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "id",
        "name",
        "mkb10",
        "states",
        "transfers"
})
@XmlRootElement(name = "graph")
public class Graph {

    @XmlElement(required = true)
    protected BigInteger id;

    @XmlElement(required = true)
    protected String name;

    @XmlElement(name = "MKB10", required = true)
    protected String mkb10;

    @XmlElement(required = true)
    protected States states;

    @XmlElement(required = true)
    protected Transfers transfers;

    public BigInteger getId() {
        return id;
    }

    public void setId(BigInteger value) {
        this.id = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getMKB10() {
        return mkb10;
    }

    public void setMKB10(String value) {
        this.mkb10 = value;
    }

    public States getStates() {
        return states;
    }

    public void setStates(States value) {
        this.states = value;
    }

    public Transfers getTransfers() {
        return transfers;
    }

    public void setTransfers(Transfers value) {
        this.transfers = value;
    }

    @Override
    public String toString() {
        return "Graph{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", mkb10='" + mkb10 + '\'' +
                ", states=" + states +
                ", transfers=" + transfers +
                '}';
    }
}
