//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.22 at 03:45:37 PM MSK
//

package ru.akrtkv.egisz.vimis.dto.vimis;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private static final QName _SendDocument_QNAME = new QName("http://vimis.rosminzdrav.ru/", "sendDocument");

    private static final QName _ReturnMsgId_QNAME = new QName("http://vimis.rosminzdrav.ru/", "returnMsgId");

    private static final QName _CheckStatus_QNAME = new QName("http://vimis.rosminzdrav.ru/", "checkStatus");

    private static final QName _CheckStatusResponse_QNAME = new QName("http://vimis.rosminzdrav.ru/", "checkStatusResponse");

    public SendDocument createSendDocument() {
        return new SendDocument();
    }

    public ReturnMsgId createReturnMsgId() {
        return new ReturnMsgId();
    }

    public CheckStatus createCheckStatus() {
        return new CheckStatus();
    }

    public CheckStatusResponse createCheckStatusResponse() {
        return new CheckStatusResponse();
    }

    public Signature createSignature() {
        return new Signature();
    }

    @XmlElementDecl(namespace = "http://vimis.rosminzdrav.ru/", name = "sendDocument")
    public JAXBElement<SendDocument> createSendDocument(SendDocument value) {
        return new JAXBElement<>(_SendDocument_QNAME, SendDocument.class, null, value);
    }

    @XmlElementDecl(namespace = "http://vimis.rosminzdrav.ru/", name = "returnMsgId")
    public JAXBElement<ReturnMsgId> createReturnMsgId(ReturnMsgId value) {
        return new JAXBElement<>(_ReturnMsgId_QNAME, ReturnMsgId.class, null, value);
    }

    @XmlElementDecl(namespace = "http://vimis.rosminzdrav.ru/", name = "checkStatus")
    public JAXBElement<CheckStatus> createCheckStatus(CheckStatus value) {
        return new JAXBElement<>(_CheckStatus_QNAME, CheckStatus.class, null, value);
    }

    @XmlElementDecl(namespace = "http://vimis.rosminzdrav.ru/", name = "checkStatusResponse")
    public JAXBElement<CheckStatusResponse> createCheckStatusResponse(CheckStatusResponse value) {
        return new JAXBElement<>(_CheckStatusResponse_QNAME, CheckStatusResponse.class, null, value);
    }
}
