//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.24 at 11:00:11 AM MSK
//

package ru.akrtkv.egisz.vimis.dto.vimis;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "summary",
        "graphs"
})
@XmlRootElement(name = "pmc")
public class Pmc {

    @XmlElement(required = true)
    protected Summary summary;

    @XmlElement(required = true)
    protected Graphs graphs;

    public Summary getSummary() {
        return summary;
    }

    public void setSummary(Summary value) {
        this.summary = value;
    }

    public Graphs getGraphs() {
        return graphs;
    }

    public void setGraphs(Graphs value) {
        this.graphs = value;
    }

    @Override
    public String toString() {
        return "Pmc{" +
                "summary=" + summary +
                ", graphs=" + graphs +
                '}';
    }
}
