//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.22 at 03:45:37 PM MSK
//

package ru.akrtkv.egisz.vimis.dto.vimis;

import javax.xml.bind.annotation.*;

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sendDocument", propOrder = {
        "vmcl",
        "docType",
        "docTypeVersion",
        "triggerPoint",
        "interimMsg",
        "signature",
        "document"
})
public class SendDocument {

    protected Integer vmcl;

    protected Integer docType;

    @XmlElement(required = true)
    protected Integer docTypeVersion;

    protected Integer triggerPoint;

    protected Integer interimMsg;

    protected Signature signature;

    @XmlElement(required = true)
    protected String document;

    public Integer getVmcl() {
        return vmcl;
    }

    public void setVmcl(Integer value) {
        this.vmcl = value;
    }

    public Integer getDocType() {
        return docType;
    }

    public void setDocType(Integer value) {
        this.docType = value;
    }

    public Integer getDocTypeVersion() {
        return docTypeVersion;
    }

    public void setDocTypeVersion(Integer value) {
        this.docTypeVersion = value;
    }

    public Integer getTriggerPoint() {
        return triggerPoint;
    }

    public void setTriggerPoint(Integer value) {
        this.triggerPoint = value;
    }

    public Integer getInterimMsg() {
        return interimMsg;
    }

    public void setInterimMsg(Integer value) {
        this.interimMsg = value;
    }

    public Signature getSignature() {
        return signature;
    }

    public void setSignature(Signature value) {
        this.signature = value;
    }

    public String getDocument() {
        return document;
    }

    public void setDocument(String value) {
        this.document = value;
    }

    @Override
    public String toString() {
        return "SendDocument{" +
                "vmcl=" + vmcl +
                ", docType=" + docType +
                ", docTypeVersion='" + docTypeVersion + '\'' +
                ", triggerPoint=" + triggerPoint +
                ", interimMsg=" + interimMsg +
                ", signature=" + signature +
                ", document='" + document + '\'' +
                '}';
    }
}
