//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.22 at 03:45:37 PM MSK
//

package ru.akrtkv.egisz.vimis.dto.vimis;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "signature", propOrder = {
        "data",
        "checksum"
})
public class Signature {

    @XmlElement(required = true)
    protected String data;

    protected int checksum;

    public String getData() {
        return data;
    }

    public void setData(String value) {
        this.data = value;
    }

    public int getChecksum() {
        return checksum;
    }

    public void setChecksum(int value) {
        this.checksum = value;
    }

    @Override
    public String toString() {
        return "Signature{" +
                "data='" + data + '\'' +
                ", checksum=" + checksum +
                '}';
    }
}
