//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.24 at 11:00:11 AM MSK
//

package ru.akrtkv.egisz.vimis.dto.vimis;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "label",
        "name",
        "description",
        "stage",
        "activities"
})
@XmlRootElement(name = "state")
public class State {

    @XmlElement(required = true)
    protected String label;

    @XmlElement(required = true)
    protected String name;

    protected String description;

    @XmlElement(required = true)
    protected String stage;

    protected Activities activities;

    public String getLabel() {
        return label;
    }

    public void setLabel(String value) {
        this.label = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String value) {
        this.description = value;
    }

    public String getStage() {
        return stage;
    }

    public void setStage(String value) {
        this.stage = value;
    }

    public Activities getActivities() {
        return activities;
    }

    public void setActivities(Activities value) {
        this.activities = value;
    }

    @Override
    public String toString() {
        return "State{" +
                "label='" + label + '\'' +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", stage='" + stage + '\'' +
                ", activities=" + activities +
                '}';
    }
}
