//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.24 at 11:00:11 AM MSK
//

package ru.akrtkv.egisz.vimis.dto.vimis;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "number",
        "text",
        "comment",
        "stage",
        "convincing",
        "evidential",
        "condition",
        "stadia",
        "tnm",
        "activities"
})
@XmlRootElement(name = "thesis-rec")
public class ThesisRec {

    protected Integer number;

    @XmlElement(required = true)
    protected String text;

    protected String comment;

    @XmlElement(required = true)
    protected String stage;

    @XmlElement(required = true)
    protected String convincing;

    @XmlElement(required = true)
    protected String evidential;

    protected String condition;

    protected String stadia;

    protected String tnm;

    protected Activities activities;

    public Integer getNumber() {
        return number;
    }

    public void setNumber(Integer value) {
        this.number = value;
    }

    public String getText() {
        return text;
    }

    public void setText(String value) {
        this.text = value;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String value) {
        this.comment = value;
    }

    public String getStage() {
        return stage;
    }

    public void setStage(String value) {
        this.stage = value;
    }

    public String getConvincing() {
        return convincing;
    }

    public void setConvincing(String value) {
        this.convincing = value;
    }

    public String getEvidential() {
        return evidential;
    }

    public void setEvidential(String value) {
        this.evidential = value;
    }

    public String getCondition() {
        return condition;
    }

    public void setCondition(String value) {
        this.condition = value;
    }

    public String getStadia() {
        return stadia;
    }

    public void setStadia(String value) {
        this.stadia = value;
    }

    public String getTnm() {
        return tnm;
    }

    public void setTnm(String value) {
        this.tnm = value;
    }

    public Activities getActivities() {
        return activities;
    }

    public void setActivities(Activities value) {
        this.activities = value;
    }

    @Override
    public String toString() {
        return "ThesisRec{" +
                "number=" + number +
                ", text='" + text + '\'' +
                ", comment='" + comment + '\'' +
                ", stage='" + stage + '\'' +
                ", convincing='" + convincing + '\'' +
                ", evidential='" + evidential + '\'' +
                ", condition='" + condition + '\'' +
                ", stadia='" + stadia + '\'' +
                ", tnm='" + tnm + '\'' +
                ", activities=" + activities +
                '}';
    }
}
