//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.24 at 11:00:11 AM MSK
//

package ru.akrtkv.egisz.vimis.dto.vimis;

import javax.xml.bind.annotation.*;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "fromState",
        "toState",
        "timeout",
        "timeoutUnit"
})
@XmlRootElement(name = "transfer")
public class Transfer {

    @XmlElement(name = "from_state")
    protected int fromState;

    @XmlElement(name = "to_state")
    protected int toState;

    protected Integer timeout;

    @XmlElement(name = "timeout_unit")
    protected String timeoutUnit;

    public int getFromState() {
        return fromState;
    }

    public void setFromState(int value) {
        this.fromState = value;
    }

    public int getToState() {
        return toState;
    }

    public void setToState(int value) {
        this.toState = value;
    }

    public Integer getTimeout() {
        return timeout;
    }

    public void setTimeout(Integer value) {
        this.timeout = value;
    }

    public String getTimeoutUnit() {
        return timeoutUnit;
    }

    public void setTimeoutUnit(String value) {
        this.timeoutUnit = value;
    }

    @Override
    public String toString() {
        return "Transfer{" +
                "fromState=" + fromState +
                ", toState=" + toState +
                ", timeout=" + timeout +
                ", timeoutUnit='" + timeoutUnit + '\'' +
                '}';
    }
}
