//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.23 at 10:13:16 AM MSK
//

package ru.akrtkv.egisz.vimis.dto.vimis.callback;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private static final QName _SendResult_QNAME = new QName("http://callback.mis.vimis.rosminzdrav.ru/", "sendResult");

    private static final QName _SendInterimMsg_QNAME = new QName("http://callback.mis.vimis.rosminzdrav.ru/", "sendInterimMsg");

    public SendResult createSendResult() {
        return new SendResult();
    }

    public SendInterimMsg createSendInterimMsg() {
        return new SendInterimMsg();
    }

    @XmlElementDecl(namespace = "http://callback.mis.vimis.rosminzdrav.ru/", name = "sendResult")
    public JAXBElement<SendResult> createSendResult(SendResult value) {
        return new JAXBElement<>(_SendResult_QNAME, SendResult.class, null, value);
    }

    @XmlElementDecl(namespace = "http://callback.mis.vimis.rosminzdrav.ru/", name = "sendInterimMsg")
    public JAXBElement<SendInterimMsg> createSendInterimMsg(SendInterimMsg value) {
        return new JAXBElement<>(_SendInterimMsg_QNAME, SendInterimMsg.class, null, value);
    }
}
