//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.09.23 at 10:13:16 AM MSK
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://callback.mis.vimis.rosminzdrav.ru/")
package ru.akrtkv.egisz.vimis.dto.vimis.callback;
